blank_issues_enabled: false
contact_links:
    - name: Community Support
      url: https://github.com/pyk/worter/discussions/new
      about: Post questions to our dicussion if you have any troubles.
